import antfu from '@antfu/eslint-config'

export default antfu({
  type: 'lib',
  lessOpinionated: true,
  jsonc: false,
  yaml: false,
  markdown: false,
  ignores: [
    '.ccg/**',
    '.codex/**',
    '.agents/plugins/**',
    '.claude-plugin/**',
    '.codex-plugin/**',
    'dist/**',
    'docs/**',
    'node_modules/**',
    'plugins/**',
    'templates/**',
  ],
}, {
  rules: {
    'curly': 'off',
    'import/consistent-type-specifier-style': 'off',
    'jsdoc/check-param-names': 'off',
    'no-console': 'off',
    'no-control-regex': 'off',
    'node/prefer-global/buffer': 'off',
    'node/prefer-global/process': 'off',
    'perfectionist/sort-exports': 'off',
    'perfectionist/sort-imports': 'off',
    'perfectionist/sort-named-exports': 'off',
    'perfectionist/sort-named-imports': 'off',
    'prefer-template': 'off',
    'regexp/no-super-linear-backtracking': 'off',
    'regexp/no-useless-character-class': 'off',
    'regexp/prefer-w': 'off',
    'style/multiline-ternary': 'off',
    'style/no-multi-spaces': 'off',
    'style/quote-props': 'off',
    'style/quotes': 'off',
    'test/prefer-lowercase-title': 'off',
    'ts/consistent-type-definitions': 'off',
    'ts/explicit-function-return-type': 'off',
  },
})
